get http://localhost:3000/api/

###

get http://localhost:3000/api/employee

###

get http://localhost:3000/api/employee/1235

###

post http://localhost:3000/api/employee
Content-Type: application/json

{
      "firstName": "Random",
      "lastName": "Drone",
      "id": 1237,
      "email": "rand2@jmail.com",
      "password": "pass",
      "roles": ["opener"],
      "permissions": "manager"
  }

###
//bad data
post http://localhost:3000/api/employee
Content-Type: application/json

{
      "firstName": "josh",
      "lastName": "hinman",
      "id": 1234,
      "password": "pass",
      "roles": ["opener"],
      "permissions": "manager"
  }

###
delete http://localhost:3000/api/employee/1235
###
//bad id delete
delete http://localhost:3000/api/employee/999

###

put http://localhost:3000/api/employee/1237
Content-Type: application/json

{
      "firstName": "Josh",
      "lastName": "Hinman",
      "id": 1237,
      "password": "pass",
      "roles": ["opener", "closer", "janitor", "CTO"],
      "permissions": "manager"
  }